config/routes.rb
Addup::Application.routes.draw do
  resources :advisors

  devise_for :admins, :controllers => { :sessions => "admins/sessions" }
  get "contact_form/new"
  get "contact_form/create"
  root :to => 'home#landingpage'
  match "/student/:id" => 'home#student_detail', :as      => :student
  match "reward/:id"   => "home#choose_your_reward", :as  => :reward
  match "terms"        => "home#terms", :as               => :terms
  match "privacy"      => "home#privacy", :as             => :privacy
  match "about"        => "home#about", :as               => :about
  match "success/:id"  => "home#thankstransf", :as        => :success
  match "application"  => 'student_applications#new', :as => :application_new
  match "contact"      => "home#contact", :as             => :contact
  match "companies"    => "home#companies", :as           => :companies
  match "howitworks"   => 'home#how_it_works', :as        => :how
  match 'ipns'         => 'donations#ipn', :as            => :ipn
  match "checkout/:id" => 'home#checkout', :as => :checkout
  match "student_application" => 'student_applications#new', :as => :application
  resources :student_applications
  match 'panel' => 'control_panel#index', :as => :panel
  match 'newform' => 'home#newform', :as => :newform
  match "faq" => 'home#faq', :as => :faq
match 'introduction' => 'home#introduction', :as => :introduction
match 'sponsors' => 'home#how_sponsors', :as => :how_sponsors

match 'faq-general' => 'home#general', :as => :faq_general
match 'faq-students' => 'home#students', :as => :faq_students
match 'faq-sponsors' => 'home#sponsors', :as => :faq_sponsors
match 'faq-addup101' => 'home#addup101', :as => :faq_addup101

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def landingpage
    unless params.blank?
      email = params[:email]
      h = Hominid::API.new("747ad60d361e1376cf91b3ff8d48a814-us5")
      begin
        @response = h.list_subscribe('af0a762abc',email,{:FNAME => '', :LNAME => ''},'html',false, true, true, false)
      rescue
        @response = nil
      end
    end
    @allstudents = StudentApplication.order("id ASC")
    @students = @allstudents.each_slice(3).to_a
    @banner = @allstudents.limit(12)
    @random = Advisor.quotes
       respond_to do |format|
        format.html
        format.js
      end
 end

  def student_detail
    @student   = StudentApplication.find(params[:id])
    #d20        = Donation.addupers(params[:id],20,50)
    #d50        = Donation.addupers(params[:id],50,75)
    #d75        = Donation.addupers(params[:id],75,100)
    #d100       = Donation.addupers(params[:id],100,10000000)
    #@donations = [[d20,"20"],[d50,"50"],[d75,"75"],[d100,"100"]]
  end

  def choose_your_reward
    @student = StudentApplication.find(params[:id])
    @donations = [20,50,75,100]
  end

  def how_it_works
  end

  def msg
  end

  def terms
  end

  def privacy
  end

def how_sponsors
end
def general
end
def students
end
def sponsors
end
def addup101
end

  def about
    @count = Donation.where(:status => "Complete").count
    @advisors = Advisor.all
  end

  def contact
    unless params.blank?
      c = ContactForm.new(:name => params["name"],:email => params["email"], :message => params["message"])
      if  c.deliver
        redirect_to root_path
      end
    end
  end

  def thankstransf
    @student = StudentApplication.find(params[:id])
    @students = StudentApplication.limit(3).order("RANDOM()")
 end

  def checkout
   logger.debug(params[:money])
   @student = StudentApplication.find(params[:id])
   @counts = @student.donations.count
   @record =  Donation.create!(:student_application_id => params[:id],:mc_gross => params[:money])
  end

  def student
  end

  def companies
    unless params.blank?
      c = MatchForm.new(:name => params["name"],:email => params["email"], :message => params["message"], :company => params["company"])
      if  c.deliver
        redirect_to root_path
      end
    end
  end

  def newform
  end

  def faq
    respond_to do |format|
      format.html
    end
  end
  def introduction
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_faqslinks.html.erb
 <%= link_to "General", faq_general_path %> | <%= link_to "Students", faq_students_path %> |  <%= link_to "Sponsors", faq_sponsors_path %> | <%= link_to "ADD UP 101", faq_addup101_path %>

app/views/home/_notified.html.erb
<div class="prospects need-funding">
  <div class="slider-questions">
    <div class="inquiry">
      <h6 class="action-text">Are you a student who wants to Add Up?</h6><br/>
      <%= link_to "Apply Now",introduction_path, :class => "button info-bg-color", :style => "text-decoration: none;" %>
    </div>
  </div>
</div>

app/views/home/_start.html.erb
<div  id="start">
  <div class="start-content-info">
    <h1>What you'll Need to apply Online</h1>
    <ul>
      <li>2 Photos for your Profile</li>
      <li>1 Video from Youtube about you</li>
      <li>University Account Information</li>
    </ul>
    <%= link_to "START >", root_path, class: "button info-bg-color", style: "text-decoration: none;" %>
  </div>
  <div class="start-content-contact">
    <h3>CONTACT US</h3>
    <%= link_to "You have question or comments?", contact_path %>
  </div>
</div>

app/views/home/about.html.erb
<div class="center">
  <div class="two-thirds">
    <h5 class="bold top-space">ABOUT US</h5>
    <h6>
At ADD UP, we believe that our world needs educated people who not only want to make an
impact on their communities, but who also genuinely believe that they have the capacity to do
so!
</h6>
<p>
The innovative turn ADD UP takes on the proven success of the crowdfunding model and the
power of social media does much more than help students raise complementary funds towards
their tuition in an easy and secure way. It also raises their confidence in their ability to be
a force for positive change. The tangible benefit may come in dollar signs, but the security
gained from knowing that others believe in them and their philanthropic pursuits is the real
reward that carries on.
</p>
<p>
  The model is a simple one. Donors are inspired by students and invest in their educational goals, with the money going directly to the student’s university account. The return on investment does not go back to the donor, but rather gets paid forward by the students in two ways: first, as they continue to add up to their communities with their abilities, talents and time and secondly, as they return 40% of what they raised to other students through the ADD UP platform over time.
</p>
<p>
If you share our vision of empowering service-oriented students, become a part of the ADD UP
community .<%= link_to "Facebook", "https://www.facebook.com/pages/AddupOrg/524068124287608?ref=ts&fref=ts" %> and <%= link_to "Twitter", "http://www.twitter.com/adduporg" %>
</p>

    <div class="team">
      <h5 class="bold top-space">THE ADD UP TEAM</h5>
      <div class="member">
        <img src="/assets/team/luly.jpg" alt="Lourdes Trevino" width=136px/>
        <h5>Lourdes Treviño</h5>
      </div>
      <div class="member">
        <img src="/assets/team/salvador.jpg" alt="Salvador Garza" width=136px height=136px/>
        <h5>Salvador Garza</h5>
      </div>

      <div class="member">
        <img src="/assets/team/joshuafrancia.jpg" alt="Joshua Francia" width=136px/>
        <h5>Joshua Francia</h5>
      </div>
       <div class="member">
        <img src="/assets/team/jorge.jpg" alt="Jorge Cuadra" width=136px/>
        <h5>Jorge Cuadra</h5>
      </div>
        <div class="member">
        <img src="/assets/team/gil.jpg" alt="Gilberto Tovar" width=136px/>
        <h5>Gilberto Tovar</h5>
      </div>
      <div class="member">
        <img src="/assets/team/mattstengel.jpg" alt= "Matt Stengel"  width=136px/>
        <h5>Matt Stengel</h5>
      </div>
 </div>

    <div class="team">
      <h5 class="bold top-space">THE ADD UP BOARD OF ADVISORS</h5>
      <% @advisors.each do |a|  %>
           <% if a.photo.nil?  %>
       <div class="member">
          <%= image_tag a.photo.thumbabout.url.to_s, :alt => a.name, :width => 136 %>
          <h5><%= a.name %></h5>
        </div>
      <% end %>
      <% end %>
    </div>
    <div class="team">
      <% @advisors.each do |a|  %>
        <% unless a.photo.nil?  %>
          <div class="member">
            <h5><%= a.name %></h5>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>
  <div class="sidebar dark-bg">
    <div class="frame light-bg">
      <span class="money"><%= @count %></span>
      <span class="label-stats">in donations</span>
    </div>

  </div>
</div>

app/views/home/companies.html.erb
<div class="center">
  <h3 class="info-color bold top-space">Interested in providing matching funds?</h3>
  <p>For students, it is invaluable for companies and successful philanthropists to believe in their education and their commitment to help society.</p>
  <p> You can reward their own fundraising efforts by matching what they raise, dollar for dollar.
  You can select the criteria for students to qualify for your matching funds, determine a maximum amount to match and even require a separate application process.</p>
  <p class="three-fifths">Contact us to learn about how your company can match funds for students.</p>
  <%= form_tag(companies_path, :method => "post", :multipart => false) do %>
    <label for="name">Full Name</label>
    <%= text_field_tag "name", nil, :id => "name" %>
    <label for="email">Email Address</label>
    <%= text_field_tag "email", nil, :id => "email" %>
    <label for="company">Company</label>
    <%= text_field_tag "company", nil, :id => "company" %>
    <label for="message">Message</label>
    <%= text_area_tag "message", nil, :id => "message" %>
    <%= submit_tag "Submit",:class => "button info-bg-color" %>
  <% end %>
</div>

app/views/home/general.html.erb
<%= content_for :javascripts do %>
  <%= stylesheet_link_tag "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag "shared" %>
  <%= javascript_include_tag "bootstrap" %>
<% end %>

<div class="center">
  <%= render "faqslinks" %>
 <h3 class="info-color bold top-space">ADD UP FAQ’s</h3>
<div id="accordion2" class="accordion">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a href="#collapseOne" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">Why was ADD UP created?</a>
    </div>
    <div class="accordion-body collapse" id="collapseOne">
      <div class="accordion-inner">
        <p>ADD UP seeks to recognize and motivate the community service efforts of international students studying for their higher education degrees in the US.</p>
        <p>Many intelligent and talented students earn their degrees and yet lack the confidence to utilize their skills and abilities in ways that can make a positive impact on their society. With the incentive of getting complementary funds towards their university’s cost of attendance, Addup.org invites students to reflect on and identify their skills and abilities, what change they are passionate about making in their community, and how they can use those talents to contribute to that change. The tangible benefit may come in dollar signs, but the security gained from knowing that people believe in them and their capacity to have a positive impact on others is the real reward that carries on.</p>
        <p>If you share our vision of empowering service-oriented students to make a positive impact in their community, become a part of the ADD UP community links to <%= link_to "Facebook", "https://www.facebook.com/pages/AddupOrg/524068124287608?ref=ts&fref=ts" %> and <%= link_to "Twitter", "http://www.twitter.com/adduporg" %>.</p>
      </div>
    </div>
  </div>

<div class="accordion-group">
          <div class="accordion-heading">
            <a href="#collapseTwo" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">What is ADD UP?</a>
          </div>
          <div class="accordion-body collapse" id="collapseTwo">
            <div class="accordion-inner">
<p>ADD UP is a platform where service-oriented, international students studying for their higher education degrees in the United States can connect with sponsors who value the impacts of both quality higher education and grassroots community service. </p>
<p>Sponsors add up to a student’s scholarship when they feel drawn to the student’s service mission, course of study, or cause. Empowered by the support of their sponsors, students then add up to their communities through any number of different community-building endeavors.  <%= render partial: 'student_applications/ideas' %>In the end, everybody wins. ADD UP simply provides the crowdfunding platform to make it all happen.</p>
</div></div></div><div class="accordion-group">
          <div class="accordion-heading">
            <a href="#collapseThree" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">Who uses ADD UP?</a>
          </div>
          <div class="accordion-body collapse" id="collapseThree">
            <div class="accordion-inner">
<ul>
<li>
Service-oriented, international students studying in the US who are seeking funds towards their higher education degree </li><li>
Family members, friends, and other supporters who want to support the student’s educational and service endeavors</li>
<li>Alumni of the student’s university</li>
<li>Anyone who supports a student’s course of study, cause, or service mission </li>
</ul>
</div></div></div><div class="accordion-group">
          <div class="accordion-heading">
            <a href="#collapseFour" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">Why are only international students eligible to utilize ADD UP right now?</a>
          </div>
          <div class="accordion-body collapse" id="collapseFour">
            <div class="accordion-inner">
<p>The United States is home to many of the best universities in the world and thus attracts hundreds of thousands of international students seeking higher education degrees each year. Though rising tuition costs affect both American and international students struggling to fund their educational goals, international students do not have access to federal and state grants and scholarships, nor are they eligible for many private scholarships that are available only to US citizens. Recognizing the lack of financial aid options available to international students, ADD UP seeks to partly fill this void by providing a crowdfunding platform which enables service-oriented international students to raise complementary funds towards their tuition and use their unique abilities to improve the community in which they study.</p>
<p>In the near future, we hope to expand the platform for American students, as we recognize that, despite the variety of financial aid options, funding their higher education is still a struggle for millions of students each year.</p>
</div></div></div><div class="accordion-group">
          <div class="accordion-heading">
            <a href="#collapseFive" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">Is ADD UP a non-profit or for-profit company?</a>
          </div>
          <div class="accordion-body collapse" id="collapseFive">
            <div class="accordion-inner">
<p>ADD UP is a for-profit company that provides a crowdfunding platform to empower sponsors and students to make a positive social impact. </p>
</div></div></div>

</div>
</div>

app/views/home/how_it_works.html.erb
<div class="center">

  <div class="student-stats">
    <h3 class="info-color bold top-space">HOW ADD UP WORKS</h3>
  </div>


  <div class="how">


    <div class="hiw clearfix">
      <h3 class="bold top-space">STUDENTS</h3>
      <div  id="row4" class="row clearfix">
        <span class="numeracion">1</span>
        <div class="how-step2 clearfix">
          <h2>Identify your skills, talents and passions to define your philanthropic project</h2>
          <p>Think about a change you would really like to see in your community. Think about a cause to which you would like to contribute. Think about your skills, your educational goals, your talents, and how you can or are using these characteristics to make the world around you a better place. Choose a way that you can add up.
          </p>
          <div class="diagram">
            <%= image_tag "how/student1.png" %>
          </div>
        </div>
      </div>
      <div  id="row5" class="row clearfix">
        <span class="numeracion">2</span>
        <div class="how-step2 clearfix">
          <h2>Make a profile that tells the world about you and your educational and philanthropic goals</h2>
          <p>Go to <%= link_to "create application",introduction_path %> to create your profile and share a little bit about who you are, your educational goals, why you care about adding up, and why you believe you have the capacity to do so. Make a short video about your social project. Choose 3-5 pictures that show potential sponsors the real you. Sign the Honor Code. Pay $25 and go live!
          </p>
          <div class="diagram">
            <%= image_tag "how/student2.png" %>
          </div>
        </div>
      </div>
      <div  id="row6" class="row clearfix">
        <span class="numeracion">3</span>
        <div class="how-step2 clearfix">
          <h2>Crowdfund your scholarship by running an engaged campaign</h2>
          <p>Share your ADD UP profile through Facebook, Twitter, mail and good-old-fashioned word of mouth (to those friends, family members, and supporters who may be behind on the whole internet revolution thing). Be creative! Make a Facebook Cause and invite your friends to join it or send out an e-card. However you go about it, don’t forget to direct people to your ADD UP profile where they can help fund your scholarship, which goes directly to your university. Your immediate network is the starting point and ADD UP will expand your network with alumni and fellow nationals. From there, every recommendation and every dollar adds up.
          </p>
          <p class="asterisk">*ADD UP utilizes PayPal to facilitate payments.</p>
          <div class="diagram">
            <%= image_tag "how/student3.png" %>
          </div>
        </div>
      </div>
    </div>


  </div>

</div>

app/views/home/introduction.html.erb
<%= content_for :javascripts do %>
  <%= stylesheet_link_tag "addup","bootstrap", :media => "all" %>
  <%= javascript_include_tag "bootstrap" %>
<% end %>

<div class="center">
  <h3 class="info-color bold top-space">  Share your story and launch a successful crowdfunding campaign!</h3>
    <p>
      Before you begin your application, make sure to gather the following things. Once you have these, your application should take no longer than 5 minutes to complete!!
    </p>
    <p>
      NOTE: All good things take time. We are in the BETA version right now, and working on developing the final product.  Therefore, the Add Up application does not have the option of saving your information and coming back to it, so you will need to complete it in one sitting. Thanks for understanding!
    </p>

      <div id="accordion2" class="accordion">
 <div class="accordion-group">
          <div class="accordion-heading">
            <a href="#collapseOne" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle"><i class="icon-hand-right"></i> A project/plan for adding up to your community!</a>
          </div>
          <div class="accordion-body collapse" id="collapseOne">
            <div class="accordion-inner">
              <ul>
                <li><i class="icon-ok"></i>Look at our social project idea generator for initial ideas to get inspired.</li><br/>
                <li> <%= render partial: 'student_applications/ideas' %></li><br/>
              </ul>
            </div>
          </div>
        </div>

 <div class="accordion-group">
          <div class="accordion-heading">
             <a href="#collapse32" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">	<i class="icon-hand-right"></i> Basic information	</a>
          </div>
          <div class="accordion-body collapse" id="collapse32">
            <div class="accordion-inner">
              <ul>
                <li><i class="icon-ok"></i>Personal information </li><br/>
                <li><i class="icon-ok"></i>Crowdfunding goal: maximum $10,000 usd </li><br/>
                <li><i class="icon-ok"></i>Total annual cost of attendance of program of study</li><br/>
                <li><i class="icon-ok"></i>Two short responses: Sharing your story and why you care about adding up</li><br/>

              </ul>
            </div>
          </div>
        </div>


 <div class="accordion-group">
          <div class="accordion-heading">
            <a href="#collapse3" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">	<i class="icon-hand-right"></i>	4-10 pictures of you	</a>
          </div>
          <div class="accordion-body collapse" id="collapse3">
            <div class="accordion-inner">
              <ul>
                <li><i class="icon-ok"></i> Pictures of you engaged in your hobbies, social activities, interests, with family, friends, etc. The objective is to help sponsors get a feel for who you are.</li><br/>
              </ul>
            </div>
          </div>
        </div>

        <div class="accordion-group">
          <div class="accordion-heading">
            <a href="#collapse4" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">	<i class="icon-hand-right"></i> A 2-minute video about your social project and why you care about care about adding up.</a>
          </div>
          <div class="accordion-body collapse" id="collapse4">
            <div class="accordion-inner">
              <ul>
                <li><i class="icon-ok"></i>Upload this video to YouTub at the Addup channel <%= link_to "click here", faq_path %>.<li><br/>
                  </ul>
                </div>
              </div>
            </div>

            <div class="accordion-group">
              <div class="accordion-heading">
                <a href="#collapse44" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">	<i class="icon-hand-right"></i> University payment information. Remember that you need to be currently enrolled or have confirmed your enrollment for the following term. </a>
              </div>
              <div class="accordion-body collapse" id="collapse44">
                <div class="accordion-inner">
                  <ul>
                    <li><i class="icon-ok"></i> Form of payment for outside scholarships: wire tranfer of check.<li<br/>
                        <ul>
                          <li><i class="icon-asterisk"></i> Wire tranfers: Name of bank, University Bank Account, ABA/routing and SWIFT</li><br/>
                          <li><i class="icon-asterisk"></i> Check: Payee's name, Financial Services Address</li><br/>
                        </ul>
                      </ul>
                      <ul>
                        <li><i class="icon-ok"></i>Student's University Reference ID </li>
                      </ul>
                    </div>
                  </div>
                </div>



             <p>
          If you want to get an idea of what your profile will look like once it goes live, check out our <%= link_to "\ demo profile" , "http://addupstaging.herokuapp.com/student/8" %>. Don’t forget to also check out our Add Up 101 for tips for launching a successful campaign. </p>

      </ul>
    </div>
          <%= link_to "START >", application_path, class: "button info-bg-color", style: "text-decoration: none;" %>

</div>

app/views/home/landingpage.html.erb
<% content_for :title do %>
  Add Up - Crowdscholarships that carry on
<% end %>
<div class="center">
<% image_tag "logo.png", :class=>"logo", :alt=>"ADD UP" %>
<%= render "banner" %>
<h1 class="action-text bold start">Start Adding Up!</h1>
<%= render "slider" %>
<% if @random != nil %>
       <ul id="ticker">
       <% @random.each do |q| %>
         <li>
         <p class="quote">"<%= q.quote  %>"</p>
         <h5 class="quote">- <%= "#{q.name}, #{q.jobp}, #{q.job}"  %></h5>
         </li>
       <% end %>
       </ul>
     <% else %>
       <p class="quote">"Your Favorite Quote"</p>
       <h5 class="quote">- Owner quote  %></h5>
     <%end%>
     <%= render "notified1" %>
     <%= render "notified" %>

   </div>

   <% content_for :scripts do %>
     <script>
       function tick(){
         $('#ticker li:first').slideUp( function () { $(this).appendTo($('#ticker')).slideDown(); });
       }
       setInterval(function(){ tick () }, 10000);
     </script>
   <% end %>

app/views/home/landingpage.js.erb
<% if @response -%>
  $("#response").html("Te inscribiste exitosamente");
<% else %>
  $("#response").html("No pudiste inscribirte, envía un email a jfrancia@boletia.com para obtener tu prueba");
<% end %>

app/views/home/thanks.html.erb
<div class="center">

			<div class="student-stats">
				<h3 class="bold top-space">Cynthia White <span class="icon checkmark"> </span></h3>
				<div class="bubble approved normal">
				</div>
				<h5>MBA Candidate (2nd year out of 4 year program)</h5>
				<h5>Georgetown University</h5>
				<h5>USA, Houston</h5>
			</div>

			<div class="full-page">
				<h2 class="info-color bold top-space">Congratulations!</h2>
				<p class="super two-thirds">
					You are now an official AddUpper of Cynthia White. Multiply the impact of your donation by sharing her story!
				</p>
				<div class="social-share left-align">
					<div class="fb-like" data-href="http://www.addup.org/student" data-send="false" data-width="300" data-show-faces="false"></div>

					<a href="https://twitter.com/share" class="twitter-share-button" data-via="twitterapi" data-lang="en">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
					<a href="mailto:info@addup.org?subject=Cynthia%20White&body=check%20this%20%0Ahttp://www.addup.org" class="button e-mail share"><span class="email-icon"></span> <span>e-mail</span></a>
				</div>
				<h5 class="recommended bold">Other Recommended Students</h5>
			</div>

			<div class="recomendations">
				<div class="window">
					<ul>
						<li>
							<a href="student.html">
							<img class="student" src="img/team/member4.jpg" alt="" />
							<div class="recomended-stats">
								<h6 class="bold"> Boris Wayne</h6>
								<h6>INDIA, Mombay</h6>
								<h6>Georgetown University</h6>
							</div>
							<span class="corner-check"> </span>
							<div class="bubble approved normal">
							</div>
							<p class="blurred" >
								I will Add Up by
							</p>
							<p class="info-color desc">
								teaching Tai Chi to people in my neighborhood
							</p>
							<div class="progress">
								<span class="achieved"> </span>
							</div>
							<p class="goals">
								<span class="highlight bold">40%</span>of Goal
							</p>
							<p class="goals">
								<span class="highlight bold">$400</span>Added Up
							</p>
							<p class="goals">
								<span class="highlight bold">14</span>days left
							</p>
							</a>
						</li>
						<li>
							<a href="student.html">
							<img class="student" src="img/team/member4.jpg" alt="" />
							<div class="recomended-stats">
								<h6 class="bold"> Boris Wayne</h6>
								<h6>INDIA, Mombay</h6>
								<h6>Georgetown University</h6>
							</div>
							<span class="corner-check"> </span>
							<div class="bubble approved normal">
							</div>
							<p class="blurred" >
								I will Add Up by
							</p>
							<p class="info-color desc">
								teaching Tai Chi to people in my neighborhood
							</p>
							<div class="progress">
								<span class="achieved"> </span>
							</div>
							<p class="goals">
								<span class="highlight bold">40%</span>of Goal
							</p>
							<p class="goals">
								<span class="highlight bold">$400</span>Added Up
							</p>
							<p class="goals">
								<span class="highlight bold">14</span>days left
							</p>

							</a>
						</li>
						<li><a href="student.html">
							<img class="student" src="img/team/member4.jpg" alt="" />
							<div class="recomended-stats">
								<h6 class="bold"> Boris Wayne</h6>
								<h6>INDIA, Mombay</h6>
								<h6>Georgetown University</h6>
							</div>
							<span class="corner-check"> </span>
							<div class="bubble approved normal">
							</div>
							<p class="blurred" >
								I will Add Up by
							</p>
							<p class="info-color desc">
								teaching Tai Chi to people in my neighborhood
							</p>
							<div class="progress">
								<span class="achieved"> </span>
							</div>
							<p class="goals">
								<span class="highlight bold">40%</span>of Goal
							</p>
							<p class="goals">
								<span class="highlight bold">$400</span>Added Up
							</p>
							<p class="goals">
								<span class="highlight bold">14</span>days left
							</p>
						</a>
						</li>

					</ul>
				</div>
			</div>

		</div>