config/routes.rb
Addup::Application.routes.draw do
  resources :advisors

  devise_for :admins, :controllers => { :sessions => "admins/sessions" }
  get "contact_form/new"
  get "contact_form/create"
  root :to => 'home#landingpage'
  match "/student/:id" => 'home#student_detail', :as      => :student
  match "reward/:id"   => "home#choose_your_reward", :as  => :reward
  match "terms"        => "home#terms", :as               => :terms
  match "privacy"      => "home#privacy", :as             => :privacy
  match "about"        => "home#about", :as               => :about
  match "success/:id"  => "home#thankstransf", :as        => :success
  match "application"  => 'student_applications#new', :as => :application_new
  match "contact"      => "home#contact", :as             => :contact
  match "companies"    => "home#companies", :as           => :companies
  match "howitworks"   => 'home#how_it_works', :as        => :how
  match 'ipns'         => 'donations#ipn', :as            => :ipn
  match "checkout/:id" => 'home#checkout', :as => :checkout
  match "student_application" => 'student_applications#new', :as => :application
  resources :student_applications
  match 'panel' => 'control_panel#index', :as => :panel
  match 'newform' => 'home#newform', :as => :newform
  match "faq" => 'home#faq', :as => :faq
match 'introduction' => 'home#introduction', :as => :introduction
match 'sponsors' => 'home#how_sponsors', :as => :how_sponsors

match 'faq-general' => 'home#general', :as => :faq_general
match 'faq-students' => 'home#students', :as => :faq_students
match 'faq-sponsors' => 'home#sponsors', :as => :faq_sponsors
match 'faq-addup101' => 'home#addup101', :as => :faq_addup101

end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  attr_accessible :email, :feedback, :job, :jobp, :name, :photo, :quote
  mount_uploader :photo, ImageUploader
  scope :quotes, order("RANDOM()")
  validates :jobp, :name, :presence => true

end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
 layout "back_end_application", :except => [:new,:create,:show]
 # GET /advisors
  # GET /advisors.json
 before_filter :authenticate_admin!, :only => [:index,:destroy,:edit]

 def index
    @advisors = Advisor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @advisors }
    end
  end

  # GET /advisors/1
  # GET /advisors/1.json
  def show
    @advisor = Advisor.find(params[:id])

    respond_to do |format|
      format.html { render  }# show.html.erb
      format.json { render json: @advisor }
    end
  end

  # GET /advisors/new
  # GET /advisors/new.json
  def new
    @advisor = Advisor.new

    respond_to do |format|
      format.html { render }# new.html.erb
      format.json { render json: @advisor }
    end
  end

  # GET /advisors/1/edit
  def edit
    @advisor = Advisor.find(params[:id])
  end

  # POST /advisors
  # POST /advisors.json
  def create
    @advisor = Advisor.new(params[:advisor])

    respond_to do |format|
      if @advisor.save
        format.html { redirect_to @advisor, notice: 'Advisor was successfully created.' }
        format.json { render json: @advisor, status: :created, location: @advisor }
      else
        format.html { render action: "new" }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /advisors/1
  # PUT /advisors/1.json
  def update
    @advisor = Advisor.find(params[:id])

    respond_to do |format|
      if @advisor.update_attributes(params[:advisor])
        format.html { redirect_to @advisor, notice: 'Advisor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advisors/1
  # DELETE /advisors/1.json
  def destroy
    @advisor = Advisor.find(params[:id])
    @advisor.destroy

    respond_to do |format|
      format.html { redirect_to advisors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/views/advisors/_form.html.erb
<%= form_for(@advisor) do |f| %>
  <% if @advisor.errors.any? %>
    <div id="error_explanation" class="alert alert-error" >
      <h2><%= pluralize(@advisor.errors.count, "error") %> prohibited this advisor from being saved:</h2>

      <ul>
      <% @advisor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<div class="row-fluid">
<label><strong>Name</strong><br/>
    <%= f.text_field :name, :class => "input-xxlarge" %>
</label>
</diV>

<div class="row-fluid">
<label><strong>Company</strong><br/>
    <%= f.text_field :job, :class => "input-xxlarge" %>
<label>
</diV>
<div class="row-fluid">
<label><strong>Job Position</strong><br/>
    <%= f.text_field :jobp, :class => "input-xxlarge" %>
<label>
</diV>


<div class="row-fluid">
<label><strong>Quote</strong><br/>
  <%= f.text_field :quote, :class => "input-xxlarge", :placeholder => "i.e Add up will allow students to share their service goals with the world!" %>
<label>
</diV>

<div class="row-fluid" >
	<div class="span6">
      <label><strong>Email</strong>
		   <div class="input-prepend">
          <span class="add-on"><i class="icon-envelope"></i></span>
          <%= f.text_field :email, :class => "span7", :placeholder => "ex. boris@hotmail.com" %>
        </label>
   		 </div>
	 </div>
     </div>


<br/>
<div class="row-fluid">
<label><strong>Photo</strong>
        <span class="help-block"> Optional </span>
    <%= f.file_field :photo %>
</label>
</diV>

  <div class="actions">
    <%= f.submit 'Send',:class => "btn btn-large btn-primary"  %>
  </div>

</div>
<% end %>

app/views/advisors/edit.html.erb
<h1>Editing advisor</h1>

<%= render 'form' %>

<%= link_to 'Show', @advisor %> |
<%= link_to 'Back', advisors_path %>

app/views/advisors/index.html.erb
<h1>Listing advisors</h1>

<table>
  <tr>
    <th>Photo</th>
    <th>Name</th>
    <th>Job</th>
    <th>Quote</th>
    <th>Email</th>
    <th>Jobp</th>
    <th>Feedback</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @advisors.each do |advisor| %>
  <tr>
    <td><%= advisor.photo %></td>
    <td><%= advisor.name %></td>
    <td><%= advisor.job %></td>
    <td><%= advisor.quote %></td>
    <td><%= advisor.email %></td>
    <td><%= advisor.jobp %></td>
    <td><%= advisor.feedback %></td>
    <td><%= link_to 'Show', advisor %></td>
    <td><%= link_to 'Edit', edit_advisor_path(advisor) %></td>
    <td><%= link_to 'Destroy', advisor, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Advisor', new_advisor_path %>

app/views/advisors/new.html.erb
<%= content_for :javascripts do %>
  <%= stylesheet_link_tag "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag "shared" %>
  <%= javascript_include_tag "bootstrap" %>
<% end %>

<% content_for :title do %>
 Board of Advisors
<% end %>

<%= render 'form' %>

app/views/advisors/show.html.erb
<p id="notice"><%= notice %></p>
<ul class="thumbnails">
  <li class="span4">
    <div class="thumbnail">
      <%= image_tag @advisor.photo_url %>
      <h3><%= @advisor.name %></h3>
      <p><%= @advisor.quote %></p>
      <dl>
        <dt>Company:</dt>
        <dd><%= @advisor.job %></dd>
        <dt>Job Position:</dt>
        <dd><%= @advisor.jobp %></dd>
        <dt>E-mail:</dt>
        <dd><%= @advisor.email %></dd>
      </dl>
      <%= link_to 'Home', root_path, :class => "btn btn-primary" %>
    </li>
  </div>
</ul>