config/routes.rb
Addup::Application.routes.draw do
  resources :advisors

  devise_for :admins, :controllers => { :sessions => "admins/sessions" }
  get "contact_form/new"
  get "contact_form/create"
  root :to => 'home#landingpage'
  match "/student/:id" => 'home#student_detail', :as      => :student
  match "reward/:id"   => "home#choose_your_reward", :as  => :reward
  match "terms"        => "home#terms", :as               => :terms
  match "privacy"      => "home#privacy", :as             => :privacy
  match "about"        => "home#about", :as               => :about
  match "success/:id"  => "home#thankstransf", :as        => :success
  match "application"  => 'student_applications#new', :as => :application_new
  match "contact"      => "home#contact", :as             => :contact
  match "companies"    => "home#companies", :as           => :companies
  match "howitworks"   => 'home#how_it_works', :as        => :how
  match 'ipns'         => 'donations#ipn', :as            => :ipn
  match "checkout/:id" => 'home#checkout', :as => :checkout
  match "student_application" => 'student_applications#new', :as => :application
  resources :student_applications
  match 'panel' => 'control_panel#index', :as => :panel
  match 'newform' => 'home#newform', :as => :newform
  match "faq" => 'home#faq', :as => :faq
match 'introduction' => 'home#introduction', :as => :introduction
match 'sponsors' => 'home#how_sponsors', :as => :how_sponsors

match 'faq-general' => 'home#general', :as => :faq_general
match 'faq-students' => 'home#students', :as => :faq_students
match 'faq-sponsors' => 'home#sponsors', :as => :faq_sponsors
match 'faq-addup101' => 'home#addup101', :as => :faq_addup101

end

app/views/layouts/_addupassets.html.erb
<%= stylesheet_link_tag "addup" %>
<%= javascript_include_tag "addup"%>

app/views/layouts/_back_end_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://addup.herokuapp.com/">Addup</a>
    2012 CrowdSchoolarShip LLC All rigths reserved
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://www.incaztech.com/">Incaztech</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_back_end_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "ADDUP", panel_path, :class=>"brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <% if admin_signed_in? %>
            <li><%= link_to "Signed in as #{current_admin.email}. Not you?",  panel_path%></li>
            <li><%= link_to "Sign out", destroy_admin_session_path, :method=> :delete, :style => "color:white" %></li>
            <li><%= link_to "Students", student_applications_path %></li>
            <li><%= link_to "Advisors", advisors_path %></li>
             <li><%= link_to "Donations", root_path %></li>
         <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_back_end_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_front_end_footer.html.erb
<div class="footer">
  <div class="center">
    <ul>
      <li><%= link_to "Contact Us", contact_path %></li>
      <li><%= link_to "About Us", about_path %></li>
      <li><%= link_to "Terms of Use", terms_path %></li>
      <li><%= link_to "Privacy Policy", privacy_path %></li>
      <li><%= link_to "Matching Funds for Companies", companies_path %></li>
      <li><%= link_to "FAQ", faq_path %></li>
    </ul>
    <ul>
      <li style="position:relative; float:left; width:120px; height:22px; margin: 0; padding: 0;">ADD UP media:</li>

      <li style="position:relative; float:left; width:93px; height:22px; margin: 0; padding: 0;">
        <div  class="fb-like" data-href="<%= root_url %>" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
    </li>

    <li style="position:relative; float:left; width:100px; height:22px; margin: 0; padding: 0; margin-top:2px; margin-left:10px;">
      <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= root_url %>" data-via="AddupOrg">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </li>
  </ul>
  <br/>
   <p class="copyright">
      2012 CrowdScholarship LLC All rights reserved
    </p>
     <p class="copyright">
       US PATENT PENDING
    </p>
 </div>
</div>
<!-- begin olark code --><script data-cfasync="false" type='text/javascript'>/*{literal}<![CDATA[*/
  window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){f[z]=function(){(a.s=a.s||[]).push(arguments)};var a=f[z]._={},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={0:+new Date};a.P=function(u){a.p[u]=new Date-a.p[0]};function s(){a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{b.contentWindow[g].open()}catch(w){c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{var t=b.contentWindow[g];t.write(p());t.close()}catch(x){b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
  /* custom configuration goes here (www.olark.com/documentation) */
  olark.identify('9102-424-10-1941');/*]]>{/literal}*/</script><noscript><a href="https://www.olark.com/site/9102-424-10-1941/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript><!-- end olark code -->

app/views/layouts/_front_end_head.html.erb
<link href='http://fonts.googleapis.com/css?family=Istok+Web' rel='stylesheet' type='text/css'>
<meta charset="utf-8" />
<%= favicon_link_tag "favicon.ico" %>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<!--To make html5 compatible with old browsers-->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<title> <%= yield :title %></title>

<!-- Javascript load -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>

app/views/layouts/_front_end_header.html.erb
<div class="lnka"><%= link_to "About Us", about_path %></div>
<div class="how2">
	<%= link_to "How it Works", how_path %>
	<div class="double-menu">
		<span>
			<%= link_to "", how_sponsors_path %>
			<%= link_to "", how_path %>
		</span>
	</div>
</div>
<div class="lnkh"><%= link_to "Create Application",  introduction_path%> </div>
<div class="lnkh"><%= link_to "Discover Students", root_path + "#discover_students" %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render "layouts/front_end_head" %>
    <%= yield :javascripts %>
    <%= render :partial => 'layouts/addupassets' unless content_for? :javascripts %>
<meta name="description" content="Add Up is a crowdscholarships platform for students to raise funds for their graduate studies in USA top universities." />
<meta name="author" content="Add Up - Crowdscholarships LLC" />
<meta name="viewport" content="width=device-width; initial-scale=1.0" />
<meta property="og:title" content=" ADD UP | Crowdscholarships LLC " />
<meta property="og:url" content="<%= root_url %>" />
<meta property="og:image" content="http://www.addup.org/assets/logo.png" />
<meta property="og:description" content="Add Up is a crowdscholarships platform for students to raise funds for their graduate studies in USA top universities." />





 </head>
  <body>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>


    <% if alert != nil %>
      <p class = "alert"><%= alert %></p>
    <% end %>
    <div class="header">
      <div class="center">
          <div class="logoh"><%= link_to image_tag('logo.png'),root_path %></div>
          <%= yield :header %>
          <%= render :partial => 'layouts/front_end_header'unless content_for? :header %>
      </div>
    </div>
      <div class="container">
        <%= yield %>
      </div>
    <%= render "layouts/front_end_footer" %>
    <%= yield :scripts %>
  </body>
</html>

app/views/layouts/back_end_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Control panel</title>
    <%= stylesheet_link_tag "bootstrap" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
 <%= favicon_link_tag "favicon.ico" %>
   <%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
    <%= render 'layouts/back_end_shim' %>
    <style type ="text/css">
      body{
        padding-top: 60px;
        padding-bottom:40;
      }
    </style>
  </head>
  <body>
  <%= render 'layouts/back_end_header' %>
   <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/forms.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Applications</title>
    <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
    <%= javascript_include_tag "bootstrap" %>
    <%= favicon_link_tag "favicon.ico" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="custumheader" >
        <div class="controls controls-row">
          <div class="span4" style="padding-top:15px;">
            <%= link_to image_tag('logo-head.png'),root_path %>
          </div>
          <h1 class="pull-right" style="padding:5px"><%= yield :title %></h1>
        </div>
      </div>
      <%= yield %>
    </div>
    <%= render "layouts/front_end_footer" %>
  </body>
</html>